name: geo-env
channels:
    - conda-forge
dependencies:
    - cartopy
    - datapane
    - flask>=2.0.0
    - flask-caching
    - gdal
    - geemap>=0.20.0
    - geopandas
    - imageio
    - ipyvtklink
    - keplergl
    - laspy
    - leafmap>=0.18.0
    - localtileserver>=0.4.0
    - osmnx
    - pip
    - pydeck
    - pyntcloud
    - python>=3.9
    - pyvista
    - requests
    - rio-cogeo
    - tifffile
