site_name: geemap
site_description: A Python package for interactive mapping with Google Earth Engine
site_author: Qiusheng Wu
site_url: https://geemap.org

repo_url: https://github.com/gee-community/geemap

copyright: "Copyright &copy; 2020 - 2024 Qiusheng Wu"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    logo: assets/logo.png
    favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          allow_errors: false
          ignore: ["conf.py"]
          execute: False
          execute_ignore:
              ["notebooks/*.ipynb", "workshops/*.ipynb", "changelog_update.py"]

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/giswqs
        - icon: fontawesome/brands/medium
          link: https://medium.com/@giswqs
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/giswqs
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/giswqs
        - icon: fontawesome/brands/youtube
          link: https://youtube.com/@giswqs
    analytics:
        provider: google
        property: G-H322CB6ZEC

nav:
    - Home: index.md
    # - Search: search_bk.md
    - Book: https://book.geemap.org
    - Installation: installation.md
    - Get Started: get-started.md
    - Usage: usage.md
    - Cheat Sheet: cheatsheet.md
    - Tutorials: tutorials.md
    - Courses: https://courses.geemap.org
    - Contributing: contributing.md
    - Citations: citations.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - YouTube Channel: https://youtube.com/@giswqs
    - Report Issues: https://github.com/gee-community/geemap/issues
    - API Reference:
          - ai module: ai.md
          - basemaps module: basemaps.md
          - cartoee module: cartoee.md
          - chart module: chart.md
          - colormaps module: colormaps.md
          - common module: common.md
          - conversion module: conversion.md
          - core module: core.md
          - datasets module: datasets.md
          - deck module: deck.md
          - ee_tile_layers module: ee_tile_layers.md
          - examples module: examples.md
          - foliumap module: foliumap.md
          - geemap module: geemap.md
          - kepler module: kepler.md
          - legends module: legends.md
          - map_widgets module: map_widgets.md
          - maplibregl module: maplibregl.md
          - ml module: ml.md
          - osm module: osm.md
          - plot module: plot.md
          - plotlymap module: plotlymap.md
          - report module: report.md
          - timelapse module: timelapse.md
          - toolbar module: toolbar.md
    - Workshops:
          - workshops/GeoPython_2021.ipynb
          - workshops/GEE_Workshop_2021.ipynb
          - workshops/SRM_Workshop_2022.ipynb
          - workshops/Crop_Mapping_2022.ipynb
          - workshops/Japan_2022.ipynb
          - workshops/GEE_Workshop_2022_Part1.ipynb
          - workshops/GEE_Workshop_2022_Part2.ipynb
          - workshops/AmericaView_2023.ipynb
          - workshops/SciPy_2023.ipynb
          - workshops/City_Plus_2023.ipynb
          - workshops/G4G_2023.ipynb
          - workshops/NCSU_2023.ipynb
          - workshops/AGU_2023.ipynb
          - workshops/Alaska_2024_Part1.ipynb
          - workshops/Alaska_2024_Part2.ipynb
          - workshops/Alaska_2024_Part3.ipynb
          - workshops/GEE_Workshop_2024.ipynb
          - workshops/TNGIC_2024.ipynb
          - workshops/IGIC_2024.ipynb
          - workshops/SciPy_2024.ipynb
          - workshops/SatMOC_2024.ipynb
          - workshops/GeoAI_2024.ipynb
          - workshops/Taiwan_2024.ipynb
          - workshops/FOSS4GNA_2024.ipynb
    - Notebooks:
          - notebooks/00_ee_auth_colab.ipynb
          - notebooks/00_geemap_colab.ipynb
          - notebooks/00_geemap_key_features.ipynb
          - notebooks/01_geemap_intro.ipynb
          - notebooks/02_using_basemaps.ipynb
          - notebooks/03_inspector_tool.ipynb
          - notebooks/04_split_panel_map.ipynb
          - notebooks/05_drawing_tools.ipynb
          - notebooks/06_marker_cluster.ipynb
          - notebooks/07_geojson.ipynb
          - notebooks/08_ee_js_to_ipynb.ipynb
          - notebooks/09_plotting.ipynb
          - notebooks/10_shapefiles.ipynb
          - notebooks/11_export_image.ipynb
          - notebooks/12_zonal_statistics.ipynb
          - notebooks/13_zonal_statistics_by_group.ipynb
          - notebooks/14_legends.ipynb
          - notebooks/15_convert_js_to_py.ipynb
          - notebooks/16_add_animated_text.ipynb
          - notebooks/17_add_colorbar_to_gif.ipynb
          - notebooks/18_create_landsat_timelapse.ipynb
          - notebooks/19_search_places_and_datasets.ipynb
          - notebooks/20_timeseries_inspector.ipynb
          - notebooks/21_export_map_to_html_png.ipynb
          - notebooks/22_import_scripts.ipynb
          - notebooks/23_import_assets.ipynb
          - notebooks/24_publish_maps.ipynb
          - notebooks/25_load_rasters.ipynb
          - notebooks/26_heroku.ipynb
          - notebooks/27_timelapse_app.ipynb
          - notebooks/28_voila.ipynb
          - notebooks/29_pydeck.ipynb
          - notebooks/30_image_props_stats.ipynb
          - notebooks/31_unsupervised_classification.ipynb
          - notebooks/32_supervised_classification.ipynb
          - notebooks/33_accuracy_assessment.ipynb
          - notebooks/34_extract_values.ipynb
          - notebooks/35_geemap_colab.ipynb
          - notebooks/36_quality_mosaic.ipynb
          - notebooks/37_pydeck_3d.ipynb
          - notebooks/38_cloud_geotiff.ipynb
          - notebooks/39_timelapse.ipynb
          - notebooks/40_ipywidgets.ipynb
          - notebooks/41_water_app.ipynb
          - notebooks/42_upload_data.ipynb
          - notebooks/43_extract_values_to_points.ipynb
          - notebooks/44_cog_stac.ipynb
          - notebooks/45_cog_mosaic.ipynb
          - notebooks/46_local_rf_training.ipynb
          - notebooks/47_image_thumbnails.ipynb
          - notebooks/48_folium_legend.ipynb
          - notebooks/49_colorbar.ipynb
          - notebooks/50_cartoee_quickstart.ipynb
          - notebooks/51_cartoee_projections.ipynb
          - notebooks/52_cartoee_gif.ipynb
          - notebooks/53_layer_vis.ipynb
          - notebooks/54_vector_vis.ipynb
          - notebooks/55_raster_vis.ipynb
          - notebooks/56_local_data.ipynb
          - notebooks/57_cartoee_blend.ipynb
          - notebooks/58_add_vector.ipynb
          - notebooks/59_whitebox.ipynb
          - notebooks/60_colormaps.ipynb
          - notebooks/61_cartoee_scalebar.ipynb
          - notebooks/62_time_slider.ipynb
          - notebooks/63_charts.ipynb
          - notebooks/64_data_catalog.ipynb
          - notebooks/65_vector_styling.ipynb
          - notebooks/66_cartoee_legend.ipynb
          - notebooks/67_training_samples.ipynb
          - notebooks/68_netcdf_to_ee.ipynb
          - notebooks/69_cartoee_vector.ipynb
          - notebooks/70_linked_maps.ipynb
          - notebooks/71_timelapse.ipynb
          - notebooks/72_time_slider_gui.ipynb
          - notebooks/73_transect.ipynb
          - notebooks/74_csv_to_points.ipynb
          - notebooks/75_sankee.ipynb
          - notebooks/76_osm_to_ee.ipynb
          - notebooks/77_planet_imagery.ipynb
          - notebooks/78_ts_inspector.ipynb
          - notebooks/79_chart_histogram.ipynb
          - notebooks/80_point_layer.ipynb
          - notebooks/81_goes_timelapse.ipynb
          - notebooks/82_contours.ipynb
          - notebooks/83_local_tile.ipynb
          - notebooks/84_openstreetmap.ipynb
          - notebooks/85_postgis.ipynb
          - notebooks/86_image_overlay.ipynb
          - notebooks/87_add_points_from_xy.ipynb
          - notebooks/88_circle_markers.ipynb
          - notebooks/89_add_labels.ipynb
          - notebooks/90_naip_timelapse.ipynb
          - notebooks/91_planetary_computer.ipynb
          - notebooks/92_plotly.ipynb
          - notebooks/93_cog_inspector.ipynb
          - notebooks/94_heremap.ipynb
          - notebooks/95_create_cog.ipynb
          - notebooks/96_image_chips.ipynb
          - notebooks/97_join_table.ipynb
          - notebooks/98_timelapse_fading.ipynb
          - notebooks/99_landsat_9.ipynb
          - notebooks/100_numpy_to_cog.ipynb
          - notebooks/101_lidar.ipynb
          - notebooks/102_blend_hillshade.ipynb
          - notebooks/103_split_control.ipynb
          - notebooks/104_clip_image.ipynb
          - notebooks/105_netcdf.ipynb
          - notebooks/106_kepler_gl.ipynb
          - notebooks/107_pydeck.ipynb
          - notebooks/108_image_zonal_stats.ipynb
          - notebooks/109_coordinate_grids.ipynb
          - notebooks/110_choropleth.ipynb
          - notebooks/111_image_count.ipynb
          - notebooks/112_cartoee_basemap.ipynb
          - notebooks/113_image_area.ipynb
          - notebooks/114_dynamic_world.ipynb
          - notebooks/115_land_cover.ipynb
          - notebooks/116_land_cover_timeseries.ipynb
          - notebooks/117_fishnet.ipynb
          - notebooks/118_download_image.ipynb
          - notebooks/119_plot_raster.ipynb
          - notebooks/120_javascript.ipynb
          - notebooks/121_vector_style.ipynb
          - notebooks/122_lidar.ipynb
          - notebooks/123_sentinel1_timelapse.ipynb
          - notebooks/124_more_datasets.ipynb
          - notebooks/125_example_code.ipynb
          - notebooks/126_inspector.ipynb
          - notebooks/127_create_legend.ipynb
          - notebooks/128_add_widget.ipynb
          - notebooks/129_vector_to_gif.ipynb
          - notebooks/130_print_objects.ipynb
          - notebooks/131_arcgis.ipynb
          - notebooks/132_folium_colorbar.ipynb
          - notebooks/133_gradio.ipynb
          - notebooks/134_ee_to_geotiff.ipynb
          - notebooks/135_segmentation.ipynb
          - notebooks/136_download_parallel.ipynb
          - notebooks/137_create_grid.ipynb
          - notebooks/138_draw_control.ipynb
          - notebooks/139_layer_to_image.ipynb
          - notebooks/140_ee_to_xarray.ipynb
          - notebooks/141_image_array_viz.ipynb
          - notebooks/142_google_maps.ipynb
          - notebooks/143_precipitation_timelapse.ipynb
          - notebooks/144_chart_features.ipynb
          - notebooks/145_chart_image.ipynb
          - notebooks/146_chart_image_collection.ipynb
          - notebooks/147_chart_array_list.ipynb
          - notebooks/148_chart_data_table.ipynb
          - notebooks/149_gemini.ipynb
          - notebooks/150_maplibre.ipynb
    #   - miscellaneous:
    #         - notebooks/cartoee_colab.ipynb
    #         - notebooks/cartoee_colorbar.ipynb
    #         - notebooks/cartoee_projections.ipynb
    #         - notebooks/cartoee_quickstart.ipynb
    #         - notebooks/cartoee_scalebar.ipynb
    #         - notebooks/cartoee_subplots.ipynb
    #         - notebooks/file_browser.ipynb
    #         - notebooks/geemap_and_earthengine.ipynb
    #         - notebooks/geemap_and_folium.ipynb
    #         - notebooks/geemap_and_ipyleaflet.ipynb
    #         - notebooks/geemap_and_ipywidgets.ipynb
    #         - notebooks/geemap_colab.ipynb
    #         - notebooks/geemap_matplotlib.ipynb
    #         - notebooks/geopandas.ipynb
    #         - notebooks/image_overlay.ipynb
    #         - notebooks/ipyleaflet_draw_control.ipynb
    #         - notebooks/ipyleaflet_tutorials.ipynb
    #         - notebooks/ipywidgets_demo.ipynb
    #         - notebooks/kml_kmz.ipynb
    #         - notebooks/local_rf_training.ipynb
    #         - notebooks/mouse_click_coordinates.ipynb
    #         - notebooks/netcdf.ipynb
    #         - notebooks/numpy_to_ee.ipynb
    #         - notebooks/nlcd_app.ipynb
    #         - notebooks/nlcd_datapane.ipynb
    #         - notebooks/notebook_template.ipynb
    #         - notebooks/oil_palm_and_rubber_plantation.ipynb
    #         - notebooks/otsu.ipynb
    #         - notebooks/qgis_layer_style_file.ipynb
    #         - notebooks/random_sampling.ipynb
    #         - notebooks/river_width.ipynb
    #         - notebooks/select_features.ipynb
    #         - notebooks/select_features_old.ipynb
    #         - notebooks/sentinel1_timelapse.ipynb
    #         - notebooks/surface_water_mapping.ipynb
    #         - notebooks/template.ipynb
    #         - notebooks/tn_surface_water.ipynb
    #         - notebooks/us_census_data.ipynb
    #         - notebooks/usda_naip_imagery.ipynb
    #         - notebooks/velocity.ipynb
    #         - notebooks/video_overlay.ipynb
    #         - notebooks/water_app.ipynb
    #         - notebooks/world_pop_density.ipynb
